/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedEscrowRouteImport } from './routes/_authenticated/escrow'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedRiskRouteImport } from './routes/_authenticated/risk'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents.$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEscrowRoute = AuthenticatedEscrowRouteImport.update({
  id: '/_authenticated/escrow',
  path: '/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/_authenticated/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/_authenticated/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRiskRoute = AuthenticatedRiskRouteImport.update({
  id: '/_authenticated/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/_authenticated/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/escrow': typeof AuthenticatedEscrowRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/escrow': typeof AuthenticatedEscrowRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/_authenticated/escrow': typeof AuthenticatedEscrowRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRoute
  '/_authenticated/risk': typeof AuthenticatedRiskRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/escrow'
    | '/fleet'
    | '/loans'
    | '/risk'
    | '/agents/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/escrow'
    | '/fleet'
    | '/loans'
    | '/risk'
    | '/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/_authenticated/escrow'
    | '/_authenticated/fleet'
    | '/_authenticated/loans'
    | '/_authenticated/risk'
    | '/_authenticated/agents/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthenticatedEscrowRoute: typeof AuthenticatedEscrowRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRoute
  AuthenticatedRiskRoute: typeof AuthenticatedRiskRoute
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/escrow': {
      id: '/_authenticated/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof AuthenticatedEscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/risk': {
      id: '/_authenticated/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthenticatedEscrowRoute: AuthenticatedEscrowRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRoute,
  AuthenticatedRiskRoute: AuthenticatedRiskRoute,
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
